# clusters/my-cluster/apps/messaging/rabbitmq-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  chart:
    spec:
      chart: rabbitmq
      version: 12.x.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  values:
    auth:
      username: user
      password: password
